/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carpark;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author lenovo
 */
public class CarExit extends javax.swing.JFrame {

    private String plakano;
    
    public CarExit(String plakano) {
        
        this.plakano = plakano;
        initComponents();
        
        try{
            
            ShowDetailsClass detail = new ShowDetailsClass(this.plakano);
            String[] details = detail.GetDetailsWithPlate();
            
            if( details == null ){

                JOptionPane.showMessageDialog(this, "Bu plakaya ait bir araç bulunamadı!", "Uyarı", JOptionPane.INFORMATION_MESSAGE);
                
            }
            
            String saatlik_fiyat = "";

            try{

                Database db = new Database();
                Connection conn = db.Connect();

                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM settings WHERE id=1");

                while(rs.next()){
                    saatlik_fiyat = rs.getString("saatlik_fiyat");
                }

            }catch(Exception error){
                System.out.println("Araç çıkış sayfasında hata:" + error);
            }
            
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
            Date date = dateFormat.parse(details[2]); // 16/05/2017 23:15
            long giris_tarihi_ts = date.getTime();

            Date datee = new Date();
            SimpleDateFormat timestamp = new SimpleDateFormat("dd/MM/yyyy HH:mm");
            String datetime = timestamp.format(datee);
            long current_ts = datee.getTime();
            
            long diff = current_ts - giris_tarihi_ts;
            long fark_saat = diff / (60 * 60 * 1000) % 24;
            long fark_dakika = diff / (60 * 1000) % 60;
            
            long ucret = Integer.parseInt(saatlik_fiyat) * (fark_saat + 1);
            
            if( fark_saat == 0 && fark_dakika == 0 ){
                ucret = 0;
            }

            this.plaka_tf.setText(plakano);
            this.giristarihi.setText(details[2]);
            this.sure.setText(fark_saat + " Saat, " + fark_dakika + " Dakika");
            this.ucret.setText(ucret + " ₺");
          
        }catch(Exception error){
            System.out.println(error);
        }
        
    }
    
    /**
     * Creates new form CarExit
    */
    public CarExit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        plaka_tf = new javax.swing.JTextField();
        giristarihi = new javax.swing.JTextField();
        sure = new javax.swing.JTextField();
        ucret = new javax.swing.JTextField();
        ucretsiz_cikis = new javax.swing.JButton();
        ücretli_cikis = new javax.swing.JButton();
        iptal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Araç Çıkışı");

        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel1.setText("Plaka:");

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel2.setText("Giriş Tarihi:");

        jLabel3.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel3.setText("Kalış Süresi:");

        jLabel4.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel4.setText("Tutar:");

        plaka_tf.setEditable(false);
        plaka_tf.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        plaka_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plaka_tfActionPerformed(evt);
            }
        });

        giristarihi.setEditable(false);
        giristarihi.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        giristarihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giristarihiActionPerformed(evt);
            }
        });

        sure.setEditable(false);
        sure.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        sure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sureActionPerformed(evt);
            }
        });

        ucret.setEditable(false);
        ucret.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        ucret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucretActionPerformed(evt);
            }
        });

        ucretsiz_cikis.setFont(new java.awt.Font("Avenir Next", 2, 14)); // NOI18N
        ucretsiz_cikis.setText("Ücret Alma");
        ucretsiz_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucretsiz_cikisActionPerformedd(evt);
            }
        });

        ücretli_cikis.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        ücretli_cikis.setText("Ücret Alındı");
        ücretli_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ücretli_cikisActionPerformed(evt);
            }
        });

        iptal.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        iptal.setText("İptal");
        iptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpark/images/arac_cikisi.png"))); // NOI18N
        jLabel5.setText("  ARAÇ ÇIKIŞI");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iptal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ucretsiz_cikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ücretli_cikis))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(plaka_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ucret, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(giristarihi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plaka_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giristarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sure, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ucret, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ücretli_cikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ucretsiz_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(iptal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        ucretsiz_cikis.getAccessibleContext().setAccessibleName("");
        iptal.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sureActionPerformed

    private void ücretli_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ücretli_cikisActionPerformed
        // TODO add your handling code here:
        try{
            
            Database db = new Database();
            Connection conn = db.Connect();

            try{

                PreparedStatement ps = conn.prepareStatement("DELETE FROM cars WHERE plaka = '"+this.plakano+"'");

                int i = ps.executeUpdate();

                if( i > 0  ){
                    JOptionPane.showMessageDialog(this, this.plakano+" plaka numaralı araç başarıyla çıkarıldı.", "Başarılı", JOptionPane.INFORMATION_MESSAGE);

                    new CarExit().setVisible(false);
                    dispose();
                    new Main().setVisible(true);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Araç Çıkarılamadı!", "HATA", JOptionPane.ERROR_MESSAGE);
                }

            }catch(Exception error){

                System.out.println("Araç çıkışı sayfasında hata:" + error);

            }
        }
        catch(Exception error){
            System.out.println("Araç çıkışı sayfasında hata:" + error);
        }

    }//GEN-LAST:event_ücretli_cikisActionPerformed

    private void ucretsiz_cikisActionPerformedd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucretsiz_cikisActionPerformedd
        // TODO add your handling code here:
        
        AdminAuthorization au = new AdminAuthorization("Ücretsiz Çıkış", this.plakano);
        au.setVisible(true);
        dispose();
        new CarExit().setVisible(false);
        dispose();
        
    }//GEN-LAST:event_ucretsiz_cikisActionPerformedd

    private void iptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptalActionPerformed
        // TODO add your handling code here:
        
        new Main().setVisible(true);
        dispose();
        new CarExit().setVisible(false);
        
    }//GEN-LAST:event_iptalActionPerformed

    
    private void ucretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucretActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ucretActionPerformed

    private void plaka_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plaka_tfActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_plaka_tfActionPerformed

    private void giristarihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giristarihiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giristarihiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarExit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField giristarihi;
    private javax.swing.JButton iptal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField plaka_tf;
    private javax.swing.JTextField sure;
    private javax.swing.JTextField ucret;
    private javax.swing.JButton ucretsiz_cikis;
    private javax.swing.JButton ücretli_cikis;
    // End of variables declaration//GEN-END:variables
}
