 
package carpark;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.*;

public class Settings extends javax.swing.JFrame {
    
    
    public Settings() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fiyat = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        admin_sifre = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        personel_sifre = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kurulum");
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel1.setText("Saatlik Ücret: ");

        fiyat.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        fiyat.setToolTipText("Lütfen yalnızca rakam kullanın. (Birim mecburi TL'dir.)");
        fiyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiyatActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jButton2.setText("Kurulumu Tamamla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel2.setText("Admin Şifresi:");

        admin_sifre.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        admin_sifre.setToolTipText("Ücret almadan araç çıkışı yapmak ve veritabanını sıfırlamak gibi bir çok ayarı bu şifre ile yapabileceksiniz.");

        jLabel3.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel3.setText("Personel Şifresi:");

        personel_sifre.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        personel_sifre.setToolTipText("Tüm personeller bu şifre ile programı açabilecek.");

        jLabel4.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpark/images/kurulum.png"))); // NOI18N
        jLabel4.setText("  KURULUM");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel4.setIconTextGap(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(personel_sifre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fiyat)
                            .addComponent(admin_sifre, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personel_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fiyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiyatActionPerformed
        
    }//GEN-LAST:event_fiyatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String admin_sifresi = new String(admin_sifre.getPassword());
        String personel_sifresi = new String(personel_sifre.getPassword());
        String saatlik_fiyati = fiyat.getText();

        try{
            
            Database db = new Database();
            Connection conn = db.Connect();

            PreparedStatement ps = conn.prepareStatement("UPDATE settings SET admin_sifre = ?, personel_sifre = ?, saatlik_fiyat = ? WHERE id = ?");
            ps.setString(1,admin_sifresi);
            ps.setString(2,personel_sifresi);
            ps.setString(3,saatlik_fiyati);
            ps.setInt(4, 1);

            int i = ps.executeUpdate();
            if( i > 0 ){
                new Settings().setVisible(false);
                new Login().setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Ayarlar güncellenemedi!", "HATA", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception error){
            JOptionPane.showMessageDialog(this, "Hata:" + error, "HATA", JOptionPane.ERROR_MESSAGE);
        }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
  
                String admin_sifre = "";
                String personel_sifre = "";
                String saatlik_fiyat = "";

                try{
                    
                    Database db = new Database();
                    Connection conn = db.Connect();
            
                    Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery("SELECT * FROM settings WHERE id=1");
                    
                    while(rs.next()){
                        admin_sifre = rs.getString("admin_sifre");
                        personel_sifre = rs.getString("personel_sifre");
                        saatlik_fiyat = rs.getString("saatlik_fiyat");
                    }
                    
                    Toolkit.getDefaultToolkit().beep();
                    System.out.println("\n======================================");
                    System.out.println("Hi!\nThe Project for Software Engineering.");
                    System.out.println("Arda Kantarcı : 2013.17.01.028");
                    System.out.println("Batuhan Kök : 2013.17.01.025");
                    System.out.println("Mustafa Kaan Araz : 2013.17.01.035");
                    System.out.println("======================================\n");
                    
                    if( personel_sifre.isEmpty() || admin_sifre.isEmpty() || saatlik_fiyat.isEmpty() )
                    {
                        new Settings().setVisible(true);
                    }
                    else
                    {
                        new Settings().setVisible(false);
                        new Login().setVisible(true);
                    }

                }catch(Exception error){
                    System.out.println("Kurulum sayfasında hata:" + error);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField admin_sifre;
    private javax.swing.JTextField fiyat;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField personel_sifre;
    // End of variables declaration//GEN-END:variables
}
